### ISSUE TITLE
Realm Swift iOS SDK, Limits primary keys with no mention in docs

### ISSUE THREAD

**Issue by samuelowino** [mongodb/docs-realm#1534]
## Is there something wrong with existing docs content, or is something missing from the docs?
Documentation does not mention that supported primary keys do not include Float and Double types.

## If this is related to existing docs content, what page or pages are affected?
https://t.co/BPKdNiHD9F

## Is this related to the MongoDB Realm backend, or an SDK? If it is an issue with an SDK, which one?
This affects the Swift iOS SDK

## What would you like to see in the docs that isn't already there?
Just a mention that the primary keys supported are limited to string, int, UUID and objectId

## Where do you feel this content belongs?
https://t.co/BPKdNiHD9F

**Comment by mongomoe** [comment]
Hey @samuelowino, thanks for letting us know that the API reference was missing that information, we appreciate your feedback. We're hoping to resolve this as soon as possible & have created a JIRA ticket to track the work to be completed on this.

I'll comment on this issue again, once I have coordinated with the Realm Swift SDK team that produces the content for the [API reference docs ](https://docs.mongodb.com/realm-sdks/swift/) so that we can get this change deployed & resolve this issue.

**Comment by mongomoe** [comment]
@samuelowino Closing this issue with a note from the SDK team that this info (i.e the types for Object.primaryKey) is available here: https://github.com/realm/realm-swift/blob/master/RealmSwift/Object.swift#L146
